### ISSUE TITLE
OpenTX 2.2 compatibility 

### ISSUE THREAD

**Issue by qp1306** [DynamikArray/KISS_Battery_Monitor#10]
I've upgraded to opentx 2.2 and the script no longer works, can it be fixed?

**Comment by lichtl** [comment]
It still work for me. Just ensure that the filename in OpenTX 2.2 is limited to 6char so KISSdata.lua is too long (rename to KISS.lua).

**Comment by qp1306** [comment]
Thanks for the reply I've done as you have said and now it's working thanks mate. 

Cheers
